name: Publish
on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install deps
        run: bun i
      - name: Build
        run: bun run build
      - name: Publish package
        run: bun run publish
